apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: eureka-server
  namespace: sit
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
      - image: 192.168.11.53:8082/risk-eureka-server-img-test:latest
        imagePullPolicy: IfNotPresent
        name: eureka-server
        ports:
        - containerPort: 8000
          hostPort: 8000
        volumeMounts:
        - mountPath: /opt/risk/service/risk-eurekaServer/logs
          name: eureka-server-log
      restartPolicy: Always
      nodeSelector:
        eureka: risk-eureka
      volumes:
      - hostPath:
          path: /app/logs/risk-sit/risk-eurekaServer
        name: eureka-server-log