apiVersion: v1
kind: Service
metadata:
  labels:
    app: eureka-server
  name: eureka-server
  namespace: sit
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: eureka-server
  type: ClusterIP