apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-risk
  namespace: sit
spec:
  ports:
  - name: tcp
    port: 5672
    protocol: TCP
    targetPort: 5672
  - name: http
    port: 15672
    protocol: TCP
    targetPort: 15672
  selector:
    app: rabbitmq-risk
  type: ClusterIP