apiVersion: v1
kind: Service
metadata:
  labels:
    app: operation-platform
  name: operation-platform
  namespace: sit
spec:
  ports:
  - port: 8890
    protocol: TCP
    targetPort: 8890
  selector:
    app: operation-platform
  type: ClusterIP