apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: operation-platform
  namespace: sit
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: operation-platform
    spec:
      containers:
      - image: 192.168.11.53:8082/risk-operation-platform-img-test:latest
        imagePullPolicy: IfNotPresent
        name: operation-platform
        ports:
        - containerPort: 8890
          hostPort: 8890
        volumeMounts:
        - mountPath: /opt/risk/service/risk-operationPlatform/logs
          name: operation-platform-log
      restartPolicy: Always
      volumes:
      - hostPath:
          path: /app/logs/risk-sit/risk-operationPlatform
        name: operation-platform-log