apiVersion: v1
kind: Service
metadata:
  name: redis-risk
  namespace: sit
spec:
  ports:
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis-risk
  type: ClusterIP