apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: eloan-dev-refactor
  namespace: dev
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: eloan-dev-refactor
    spec:
      containers:
      - image: 192.168.11.53:8082/eloan-dev-refactor:2.1.0
        imagePullPolicy: IfNotPresent
        name: eloan-dev-refactor
        ports:
        - containerPort: 8080
          hostPort: 9999
          name: eloan-refactor
          protocol: TCP
        volumeMounts:
        - mountPath: /usr/local/tomcat/logs
          name: eloan-portal-refactor-log
        - mountPath: /home/tomcat/pageUpload
          name: eloan-page-upload
      restartPolicy: Always
      nodeSelector:
        app: eloan-dev-refactor
      volumes:
      - hostPath:
          path: /app/logs/eloan-portal-refactor
        name: eloan-portal-refactor-log
      - name: eloan-page-upload
        nfs:
          path: /volume1/eloan-attachment-dev/pageUpload
          server: 192.168.3.64