apiVersion: v1
kind: Service
metadata:
  labels:
    app: dispatch-center
  name: dispatch-center
  namespace: sit
spec:
  ports:
  - port: 8818
    protocol: TCP
    targetPort: 8818
  selector:
    app: dispatch-center
  type: ClusterIP