apiVersion: v1
kind: Service
metadata:
  labels:
    run: rabbitmq-service-prod
  name: rabbitmq-service-prod
  namespace: prod
spec:
  ports:
  - name: tcp
    port: 5672
    protocol: TCP
    targetPort: 5672
  - name: http
    port: 15672
    protocol: TCP
    targetPort: 15672
  selector:
    app: rabbitmq-prod
  type: ClusterIP
