apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  namespace: sit
spec:
  clusterIP: 10.254.22.15
  ports:
  - name: redis
    nodePort: 31123
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis-sit
  type: NodePort
