apiVersion: v1
kind: Service
metadata:
  labels:
    app: model-score
  name: model-score
  namespace: sit
spec:
  ports:
  - port: 8825
    protocol: TCP
    targetPort: 8825
  selector:
    app: model-score
  type: ClusterIP