apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: data-treating
  namespace: sit
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: data-treating
    spec:
      containers:
      - image: 192.168.11.53:8082/risk-data-treating-img-test:latest
        imagePullPolicy: IfNotPresent
        name: data-treating
        ports:
        - containerPort: 8801
          hostPort: 8801
        volumeMounts:
        - mountPath: /opt/risk/service/risk-data-treating/logs
          name: data-treating-log
      restartPolicy: Always
      volumes:
      - hostPath:
          path: /app/logs/risk-sit/risk-data-treating
        name: data-treating-log