apiVersion: v1
kind: Service
metadata:
  labels:
    app: data-treating
  name: data-treating
  namespace: sit
spec:
  ports:
  - port: 8801
    protocol: TCP
    targetPort: 8801
  selector:
    app: data-treating
  type: ClusterIP