apiVersion: v1
kind: Service
metadata:
  labels:
    app: data-cleaning
  name: data-cleaning
  namespace: sit
spec:
  ports:
  - port: 7701
    protocol: TCP
    targetPort: 7701
  selector:
    app: data-cleaning
  type: ClusterIP