apiVersion: v1
kind: Service
metadata:
  labels:
    app: data-model-treating
  name: data-model-treating
  namespace: sit
spec:
  ports:
  - port: 5501
    protocol: TCP
    targetPort: 5501
  selector:
    app: data-model-treating
  type: ClusterIP