apiVersion: v1
kind: Service
metadata:
  name: mysql-sit
  namespace: sit
spec:
  ports:
  - name: mysql
    nodePort: 31010
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql
  type: NodePort
