apiVersion: v1
kind: Service
metadata:
  labels:
    app: vis-perf
  name: vis-perf
  namespace: performance
spec:
  ports:
  - port: 8083
    protocol: TCP
    targetPort: 8083
  selector:
    app: vis-perf
  type: ClusterIP