apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service-sit
  namespace: sit
spec:
  clusterIP: 10.254.22.16
  ports:
  - name: tcp
    nodePort: 31811
    port: 5672
    protocol: TCP
    targetPort: 5672
  - name: http
    nodePort: 31812
    port: 15672
    protocol: TCP
    targetPort: 15672
  selector:
    app: rabbitmq-sit
  type: NodePort
