apiVersion: v1
kind: Service
metadata:
  labels:
    app: channel-service
  name: channel-service
  namespace: sit
spec:
  ports:
  - port: 8833
    protocol: TCP
    targetPort: 8833
  selector:
    app: channel-service
  type: ClusterIP