apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: channel-service
  namespace: sit
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: channel-service
    spec:
      containers:
      - image: 192.168.11.53:8082/risk-channel-service-img-test:latest
        imagePullPolicy: IfNotPresent
        name: channel-service
        ports:
        - containerPort: 8833
          hostPort: 8833
        volumeMounts:
        - mountPath: /opt/risk/service/risk-channelService/logs
          name: channel-service-log
      restartPolicy: Always
      volumes:
      - hostPath:
          path: /app/logs/risk-sit/risk-channelService
        name: channel-service-log