apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-0-local-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /app/mysql-0
