apiVersion: v1
kind: Service
metadata:
  labels:
    app: qualify
  name: qualify
  namespace: sit
spec:
  ports:
  - port: 8899
    protocol: TCP
    targetPort: 8899
  selector:
    app: qualify
  type: ClusterIP