apiVersion: v1
kind: Service
metadata:
  labels:
    app: cwbi-portal
  name: cwbi-portal
  namespace: sit
spec:
  ports:
  - port: 8181
    protocol: TCP
    targetPort: 8090
  selector:
    app: cwbi-portal
  type: ClusterIP