apiVersion: v1
kind: Service
metadata:
  labels:
    app: auto-approval
  name: auto-approval
  namespace: sit
spec:
  ports:
  - port: 8866
    protocol: TCP
    targetPort: 8866
  selector:
    app: auto-approval
  type: ClusterIP