apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: auto-approval
  namespace: sit
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: auto-approval
    spec:
      containers:
      - image: 192.168.11.53:8082/risk-auto-approval-img-test:latest
        imagePullPolicy: IfNotPresent
        name: auto-approval
        ports:
        - containerPort: 8866
          hostPort: 8866
        volumeMounts:
        - mountPath: /opt/risk/service/risk-autoApproval/logs
          name: auto-approval-log
      restartPolicy: Always
      volumes:
      - hostPath:
          path: /app/logs/risk-sit/risk-autoApproval
        name: auto-approval-log