FROM 192.168.11.53:8082/tomcat:7.0.86-jre7-alpine
MAINTAINER RayHsu
WORKDIR /usr/local
COPY msyhbd.ttf /usr/share/fonts/
COPY msyh.ttf /usr/share/fonts/
COPY context.xml tomcat/conf/
RUN rm -rf tomcat/webapps/* && \
    mkdir -p /mfbmsDataFile/signaturesFile/eloan /home/tomcat/upload /home/tomcat/reportUpload /home/tomcat/invitationQrCodeUpload && \
    sed -i '136a<Context debug="0" docBase="/mfbmsDataFile/signaturesFile/eloan/" path="/cpf" reloadable="false"/>' tomcat/conf/server.xml
ADD eloan.war tomcat/webapps/
ADD Shanghai ./
ADD tomcat-lib/commons-pool2-2.4.2.jar tomcat/lib/
ADD tomcat-lib/jedis-2.8.1-SNAPSHOT.jar tomcat/lib/
ADD tomcat-lib/tomcat-redis-session-manager-2.0.0.jar tomcat/lib/
RUN echo "Asia/Shanghai" > /etc/timezone && \
    cp Shanghai /etc/localtime && \
    mv tomcat/webapps/eloan.war  tomcat/webapps/ROOT.war
CMD ["catalina.sh", "run"]