apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis-dev
  namespace: dev
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-dev
    spec:
      containers:
      - image: 192.168.11.53:8082/redis-dev:T2
        imagePullPolicy: Always
        name: redis
        ports:
        - containerPort: 6379
          hostPort: 6379
          protocol: TCP
      nodeSelector:
        node: redis
      restartPolicy: Always
