apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  namespace: dev
spec:
  clusterIP: 10.254.12.15
  ports:
  - name: redis
    nodePort: 31113
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis-dev
  type: NodePort
