apiVersion: v1
kind: Service
metadata:
  labels:
    app: platform-service
  name: platform-service
  namespace: sit
spec:
  ports:
  - port: 8811
    protocol: TCP
    targetPort: 8811
  selector:
    app: platform-service
  type: ClusterIP