apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: platform-service
  namespace: sit
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: platform-service
    spec:
      containers:
      - image: 192.168.11.53:8082/risk-platform-service-img-test:latest
        imagePullPolicy: IfNotPresent
        name: platform-service
        ports:
        - containerPort: 8811
          hostPort: 8811
        volumeMounts:
        - mountPath: /opt/risk/service/risk-platformService/logs
          name: platform-service-log
      restartPolicy: Always
      volumes:
      - hostPath:
          path: /app/logs/risk-sit/risk-platformService
        name: platform-service-log