apiVersion: v1
data:
  default.conf: |
    upstream lbpm-portal {
     server 192.168.11.54:8888;
     }

    server {
        listen       80;
        server_name  localhost;
        location / {
          proxy_pass http://lbpm-portal;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_http_version 1.1;
          proxy_connect_timeout 159s;
          proxy_send_timeout   600;
          proxy_read_timeout   600;
        }


        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }



    }
kind: ConfigMap
metadata:
  creationTimestamp: 2018-06-01T04:25:21Z
  name: nginx-default-conf
  namespace: prod
  resourceVersion: "1964513"
  selfLink: /api/v1/namespaces/prod/configmaps/nginx-default-conf
  uid: cc26c05d-6553-11e8-b6bc-005056a9fe78
