apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: business-api
  namespace: sit
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: business-api
    spec:
      containers:
      - image: 192.168.11.53:8082/risk-business-api-img-test:latest
        imagePullPolicy: IfNotPresent
        name: business-api
        ports:
        - containerPort: 8823
          hostPort: 8823
        volumeMounts:
        - mountPath: /opt/risk/service/risk-businessAPI/logs
          name: business-api-log
      restartPolicy: Always
      volumes:
      - hostPath:
          path: /app/logs/risk-sit/risk-businessAPI
        name: business-api-log