apiVersion: v1
kind: Service
metadata:
  labels:
    app: business-api
  name: business-api
  namespace: sit
spec:
  ports:
  - port: 8823
    protocol: TCP
    targetPort: 8823
  selector:
    app: business-api
  type: ClusterIP