apiVersion: v1
kind: Service
metadata:
  name: mysql-prod
  namespace: prod
spec:
  clusterIP: 10.254.11.14
  ports:
  - name: mysql
    nodePort: 31010
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql-prod
  type: NodePort
