apiVersion: v1
kind: Service
metadata:
  name: redis-prod
  namespace: prod
spec:
  clusterIP: 10.254.11.15
  ports:
  - name: redis
    nodePort: 31009
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis-prod
  type: NodePort
