apiVersion: v1
kind: Service
metadata:
  name: redis-prod
  namespace: prod
spec:
  ports:
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis-prod
  type: ClusterIP