apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: redis-prod
  name: redis-prod
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-prod
  template:
    metadata:
      labels:
        app: redis-prod
    spec:
      containers:
      - image: 192.168.11.53:8082/redis-prod
        imagePullPolicy: Always
        name: redis
        ports:
        - containerPort: 6379
          hostPort: 6379
          protocol: TCP
      nodeSelector:
        node: redis
      restartPolicy: Always