apiVersion: v1
kind: Service
metadata:
  labels:
    app: job
  name: job
  namespace: sit
spec:
  ports:
  - port: 8820
    protocol: TCP
    targetPort: 8820
  selector:
    app: job
  type: ClusterIP